call plug#begin('~/.vim/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
" Plugin para cerrar automáticamente (), [], {}, '', ""
Plug 'Raimondi/delimitMate'
" Plugin para colorear paréntesis, corchetes y llaves por nivel
Plug 'luochen1990/rainbow'
" Plugin de temas
Plug 'morhetz/gruvbox'
Plug 'dracula/vim', { 'as': 'dracula' }
Plug 'arcticicestudio/nord-vim'
Plug 'sickill/vim-monokai'
Plug 'joshdick/onedark.vim'
" para black
Plug 'psf/black', { 'branch': 'stable' }
Plug 'mattn/emmet-vim'

call plug#end()

" Configuración de esquemas de color
set background=dark
colorscheme nord
" Cambia 'nord gruvbox dracula monokai onedark' por el esquema que prefieras

" Configuraciones adicionales
set number
syntax on
set hlsearch
set mouse=a
set completeopt=menuone,noinsert,noselect
set tabstop=4
set shiftwidth=4
set expandtab

" Resaltar la línea del cursor
set cursorline
" Personalizar el color de la línea del cursor
highlight CursorLine term=bold cterm=bold guibg=Grey40

" Ejecutar Black al guardar archivos Python sin notificaciones
autocmd BufWritePre *.py silent! execute ':silent! %!black -q -'

" Configuración de rainbow
let g:rainbow_active = 1

" Configuración para archivos .txt
autocmd BufNewFile,BufRead *.txt set syntax=txt
" Definir reglas de resaltado de sintaxis para archivos .txt
augroup txt_syntax
  autocmd!
  " Resaltar palabras clave como TODO y FIXME
  autocmd Syntax txt syntax match TextTodo "\<TODO\>"
  autocmd Syntax txt highlight TextTodo ctermfg=yellow guifg=yellow
  autocmd Syntax txt syntax match TextFixme "\<FIXME\>"
  autocmd Syntax txt highlight TextFixme ctermfg=red guifg=red
  " Resaltar cadenas de texto entre comillas
  autocmd Syntax txt syntax match TextString "\"[^\"]*\""
  autocmd Syntax txt highlight TextString ctermfg=green guifg=green
  " Resaltar números
  autocmd Syntax txt syntax match TextNumber "\<[0-9]\+\>"
  autocmd Syntax txt highlight TextNumber ctermfg=cyan guifg=cyan
  " Resaltar comentarios (líneas que comienzan con #)
  autocmd Syntax txt syntax match TextComment "^#.*"
  autocmd Syntax txt highlight TextComment ctermfg=blue guifg=blue
  " Resaltar direcciones de correo electrónico
  autocmd Syntax txt syntax match TextEmail "\<[a-zA-Z0-9._%+-]\+@[a-zA-Z0-9.-]\+\.[a-zA-Z]\{2,}\>"
  autocmd Syntax txt highlight TextEmail ctermfg=magenta guifg=magenta
augroup END

set nobackup
" No crear archivos de respaldo
set nowritebackup
" No crear respaldo al guardar
set noswapfile
" No crear archivo de intercambio

set scroll=3
" Número de líneas para desplazar con Ctrl-U y Ctrl-D
set sidescroll=0
" Número de columnas para desplazar horizontalmente

" Aumentar la velocidad de desplazamiento en Vim
set updatetime=300
" Reduce el tiempo de actualización para una respuesta más rápida
set lazyredraw
" Evita el redibujado de la pantalla mientras se mueve el cursor

" Ajustar el tamaño del buffer para una respuesta más rápida
set ttyfast
" Optimiza el rendimiento del terminal
" Ajustar la cantidad de líneas de desplazamiento para mejor velocidad
set scrolljump=3
" Cuántas líneas se saltan cuando se usa Ctrl-U/D
set scrolloff=0
" Cuántas líneas mantener visibles alrededor del cursor

" Formateo
command! Black execute '!black % > /dev/null 2>&1'

autocmd BufWritePre *.js,*.css,*.html,*.json execute 'silent! write | call system("prettier --write " . shellescape(expand("%"))) | edit!'

" Para auto completado
autocmd FileType html,css,json setlocal omnifunc=CocActionAsync
inoremap <silent><expr> <CR> pumvisible() ? coc#_select_confirm() : "\<CR>"


" Habilitar autocompletado para Python con Coc.nvim
autocmd FileType python setlocal omnifunc=CocActionAsync

